metadata:
  favicon: ''
  title: ILP Bulk Targets
  description: ''
  breakpoints: []
  rendererCachingEnabled: true
  skipDepsComparisonInCompilerCache: false
appSettings:
  properties:
    defaultData: '{}'
  actions:
    appLoad:
      - action: '17244047870500.5843948586976926'
        paramCode: ''
        blockPageLoad: false
        preventDefault: false
        index: 0
    appData: []
  gridVersion: 2
  density: compact
internalType: project
